version: '3'
services:
  webserver:
    build: ./
    image: node-express-dev:1.0
    container_name: node
    working_dir: /home/node
    tty: true
    environment:
        - NODE_ENV=production
    volumes:
      - ./:/home/node
    ports:
      - "8080:3000"