version: '3'
services:
  webserver:
    build: node
    image: node-express-dev:1.0
    container_name: node
    working_dir: /home/node
    tty: true
    volumes:
      - ./:/home/node
    ports:
      - "8080:3000"